#!/bin/bash


MYIP=$(wget -qO- ipv4.icanhazip.com)
echo "------------------------------- MEMBUAT AKUN SSH & ovpn -------------------------------"

if [[ $vps = "soned" ]]; then
	echo "                                                "
	echo "                           "
else
	echo "                                                 "
	echo "                "
fi

	echo "                   "
echo ""

read -p "Isikan username: " username

egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
	echo "Username [$username] sudah ada!"
	exit 1
else
	read -p "Isikan password akun [$username]: " password
	read -p "Berapa hari akun [$username] aktif: " AKTIF

	today="$(date +"%Y-%m-%d")"
	expire=$(date -d "$AKTIF days" +"%Y-%m-%d")
	useradd -M -N -s /bin/false -e $expire $username
	echo $username:$password | chpasswd

	echo ""
	echo "-----------------------------------"
	echo "Data Login:"
	echo "-----------------------------------"
	echo "Host/IP: $MYIP"
	echo "Dropbear Port: 443, 110, 109"
	echo "OpenSSH Port: 22, 143"
	echo "Squid Proxy: 8080, 3128"
	echo "Username: $username"
	echo "Password: $password"
	echo "Valid s/d: $(date -d "$AKTIF days" +"%d-%m-%Y")"
	echo "-----------------------------------"
	echo ""
	echo "     script by: jucky vengeance     "	
fi

cd ~/
rm -f /root/IP
